name: Build EXE

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build EXE
        run: |
          cl /nologo /O2 /MT appinfo-uac-wd-exclude.c ^
            advapi32.lib ^
            shell32.lib ^
            user32.lib ^
            ntdll.lib ^
            rpcrt4.lib ^
            /Fe:appinfo-uac-wd-exclude.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appinfo-uac-wd-exclude
          path: appinfo-uac-wd-exclude.exe
