name: Build EXE

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc

      - name: Build
        shell: msys2 {0}
        run: |
          gcc appinfo-uac-wd-exclude.c -o appinfo-uac-wd-exclude.exe -static

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: appinfo-uac-wd-exclude.exe
